- name: Unp profile and ISID
  hosts: all
  connection: network_cli
  become: true
  gather_facts: no
  tasks:
    - name: Retrieve unp profile with its ISID
      cli_command:
       command: show configuration snapshot da-unp
#       command: show configuration snapshot da-unp | grep unp-dd
      register: unp_output
      ignore_errors: true

    - name: show unp output
      set_fact:
        unp_profiles: "{{ unp_output.stdout_lines | select('match', '^unp profile \"(.*)\"( map.*)? isid (\\d+)(.*)?$') | map('regex_replace', '^unp profile \"(.*)\"( map.*)? isid (\\d+)(.*)?$', '\\1: \\3') | list }}"

    - name: Print unp profiles
      debug:
        var: unp_profiles

    - name: Compare expected and actual unp profiles
      assert:
        that:
          - "{{ unp_profiles == ['unp-ap: 10110', 'unp-mgmt: 104003', 'unp-user: 10110', 'unp-voip: 10191', 'unp-guest: 10110', 'unp-extern: 40383', 'unp-printer: 10110', 'unp-internet: 90925', 'unp-user-110: 10110', 'unp-user-130: 10130'] }}"
